<?php 

/*
* Implements: Hook Form Alter
* Triggers callback _newsjl_up_image
* after saving/updating node of type "News"
*/
function newsjl_update_image_form_alter(&$form, &$form_state, $form_id) {
    // Checking form_id
    if ($form_id == 'news_node_form') {
        // Adding custom callback function.
        $form['actions']['submit']['#submit'][] = '_newsjl_up_image';
    }
}

/*
* News Callback Function to Dynamically set a default image 
* if editor doesn't set one after saving/updating 
* node of type "News"
*/
function _newsjl_up_image($form, &$form_state) {

    // Load Node News Info and Tag Term
	$nid = $form_state['values']['nid'];
    $node = node_load($nid);
    $tagId = $node->field_tag['und'][0]['tid'];
    $termTag = taxonomy_term_load($tagId);
    $nameTag = $termTag->name;

    if (!empty($nameTag) && isset($nameTag)) {
        $imageUnsplash = "https://api.unsplash.com/search/photos?query=".$nameTag."&client_id=267affd5fda2244900a77847d52fb57ab0b3efa12ab166d0947bf9838795902b&page=1&per_page=1";
        $ch = curl_init();
        curl_setopt ($ch, CURLOPT_URL, $imageUnsplash);
        curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
        $imageUnsplashContents = curl_exec($ch);
        curl_close($ch);

        if (!empty($imageUnsplashContents) && isset($imageUnsplashContents)) {
            $json_response = drupal_json_decode($imageUnsplashContents);
            $newsImage = $json_response['results'];
            $newsImageUrl = $newsImage[0]['urls']['raw'];
        
            if ((!empty($node) && isset($node)) && (empty($node->field_image) || !isset($node->field_image)) && (!empty($newsImageUrl) && isset($newsImageUrl)) ) {
                $filename = $node->title.'.jpg';
                $image_object = file_get_contents($newsImageUrl.'&fit=crop&w=900&h=900');
                $file = file_save_data($image_object, 'public://' . $filename, FILE_EXISTS_RENAME);
                $file->uid = $node->uid;
                $node->field_image['und'][0] = (array)$file;
                field_attach_update('node', $node);
            }
        }
    }
    
    
}